services:
  postgres:
    image: postgres
    container_name: postgresDB
    environment:
      POSTGRES_USER: mariliadb
      POSTGRES_PASSWORD: passworddb
      POSTGRES_DB: nestdb
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: Livro_API
    env_file: .env
    ports:
      - '${API_PORT2}:${API_PORT2}'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL_CONTAINER} 
    command: sh -c "npx prisma migrate deploy && npm run start:prod"